use keys;
use layout::Layout;


pub fn us() -> Layout {
    Layout {
        has_alt_gr_key: false,
        key_symbol_map: hashmap!{
            (0, 0, keys::KEY_1) => '1',
            (0, 1, keys::KEY_1) => '!',
            (0, 0, keys::KEY_2) => '2',
            (0, 1, keys::KEY_2) => '@',
            (0, 0, keys::KEY_3) => '3',
            (0, 1, keys::KEY_3) => '#',
            (0, 0, keys::KEY_4) => '4',
            (0, 1, keys::KEY_4) => '$',
            (0, 0, keys::KEY_5) => '5',
            (0, 1, keys::KEY_5) => '%',
            (0, 0, keys::KEY_6) => '6',
            (0, 1, keys::KEY_6) => '^',
            (0, 0, keys::KEY_7) => '7',
            (0, 1, keys::KEY_7) => '&',
            (0, 0, keys::KEY_8) => '8',
            (0, 1, keys::KEY_8) => '*',
            (0, 0, keys::KEY_9) => '9',
            (0, 1, keys::KEY_9) => '(',
            (0, 0, keys::KEY_0) => '0',
            (0, 1, keys::KEY_0) => ')',
            (0, 0, keys::KEY_HYPHEN) => '-',
            (0, 1, keys::KEY_HYPHEN) => '_',
            (0, 0, keys::KEY_EQUALS) => '=',
            (0, 1, keys::KEY_EQUALS) => '+',
            (0, 0, keys::KEY_Q) => 'q',
            (0, 1, keys::KEY_Q) => 'Q',
            (0, 0, keys::KEY_W) => 'w',
            (0, 1, keys::KEY_W) => 'W',
            (0, 0, keys::KEY_E) => 'e',
            (0, 1, keys::KEY_E) => 'E',
            (0, 0, keys::KEY_R) => 'r',
            (0, 1, keys::KEY_R) => 'R',
            (0, 0, keys::KEY_T) => 't',
            (0, 1, keys::KEY_T) => 'T',
            (0, 0, keys::KEY_Y) => 'y',
            (0, 1, keys::KEY_Y) => 'Y',
            (0, 0, keys::KEY_U) => 'u',
            (0, 1, keys::KEY_U) => 'U',
            (0, 0, keys::KEY_I) => 'i',
            (0, 1, keys::KEY_I) => 'I',
            (0, 0, keys::KEY_O) => 'o',
            (0, 1, keys::KEY_O) => 'O',
            (0, 0, keys::KEY_P) => 'p',
            (0, 1, keys::KEY_P) => 'P',
            (0, 0, keys::KEY_OP_BRACKET) => '[',
            (0, 1, keys::KEY_OP_BRACKET) => '{',
            (0, 0, keys::KEY_CL_BRACKET) => ']',
            (0, 1, keys::KEY_CL_BRACKET) => '}',
            (0, 0, keys::KEY_A) => 'a',
            (0, 1, keys::KEY_A) => 'A',
            (0, 0, keys::KEY_S) => 's',
            (0, 1, keys::KEY_S) => 'S',
            (0, 0, keys::KEY_D) => 'd',
            (0, 1, keys::KEY_D) => 'D',
            (0, 0, keys::KEY_F) => 'f',
            (0, 1, keys::KEY_F) => 'F',
            (0, 0, keys::KEY_G) => 'g',
            (0, 1, keys::KEY_G) => 'G',
            (0, 0, keys::KEY_H) => 'h',
            (0, 1, keys::KEY_H) => 'H',
            (0, 0, keys::KEY_J) => 'j',
            (0, 1, keys::KEY_J) => 'J',
            (0, 0, keys::KEY_K) => 'k',
            (0, 1, keys::KEY_K) => 'K',
            (0, 0, keys::KEY_L) => 'l',
            (0, 1, keys::KEY_L) => 'L',
            (0, 0, keys::KEY_COLON) => ';',
            (0, 1, keys::KEY_COLON) => ':',
            (0, 0, keys::KEY_QUOTE) => '\'',
            (0, 1, keys::KEY_QUOTE) => '\"',
            (0, 0, keys::KEY_BACKTICK) => '`',
            (0, 1, keys::KEY_BACKTICK) => '~',
            (0, 0, keys::KEY_HASH) => '\\',
            (0, 1, keys::KEY_HASH) => '|',
            (0, 0, keys::KEY_Z) => 'z',
            (0, 1, keys::KEY_Z) => 'Z',
            (0, 0, keys::KEY_X) => 'x',
            (0, 1, keys::KEY_X) => 'X',
            (0, 0, keys::KEY_C) => 'c',
            (0, 1, keys::KEY_C) => 'C',
            (0, 0, keys::KEY_V) => 'v',
            (0, 1, keys::KEY_V) => 'V',
            (0, 0, keys::KEY_B) => 'b',
            (0, 1, keys::KEY_B) => 'B',
            (0, 0, keys::KEY_N) => 'n',
            (0, 1, keys::KEY_N) => 'N',
            (0, 0, keys::KEY_M) => 'm',
            (0, 1, keys::KEY_M) => 'M',
            (0, 0, keys::KEY_COMMA) => ',',
            (0, 1, keys::KEY_COMMA) => '<',
            (0, 0, keys::KEY_PERIOD) => '.',
            (0, 1, keys::KEY_PERIOD) => '>',
            (0, 0, keys::KEY_NUM_MUL) => '*',
            (0, 1, keys::KEY_NUM_MUL) => '*',
            (0, 0, keys::KEY_F_SLASH) => '/',
            (0, 1, keys::KEY_F_SLASH) => '?',
            (0, 0, keys::KEY_SPACE) => ' ',
            (0, 1, keys::KEY_SPACE) => ' ',
            (0, 1, keys::KEY_NUM_7) => '7',
            (0, 1, keys::KEY_NUM_8) => '8',
            (0, 1, keys::KEY_NUM_9) => '9',
            (0, 0, keys::KEY_NUM_SUB) => '-',
            (0, 1, keys::KEY_NUM_SUB) => '-',
            (0, 1, keys::KEY_NUM_4) => '4',
            (0, 1, keys::KEY_NUM_5) => '5',
            (0, 1, keys::KEY_NUM_6) => '6',
            (0, 0, keys::KEY_NUM_ADD) => '+',
            (0, 1, keys::KEY_NUM_ADD) => '+',
            (0, 1, keys::KEY_NUM_1) => '1',
            (0, 1, keys::KEY_NUM_2) => '2',
            (0, 1, keys::KEY_NUM_3) => '3',
            (0, 1, keys::KEY_NUM_0) => '0',
            (0, 1, keys::KEY_NUM_DECIMAL) => '.',
            (0, 0, keys::KEY_NUM_DIV) => '/',
            (0, 1, keys::KEY_NUM_DIV) => '/',
        }
    }
}
